-- ==============================================================================
-- FEA ATELIER SPATIAL SHOWROOM — SEED DATA FOR SUPABASE
-- ==============================================================================

INSERT INTO hero_settings (id, hero_image_url)
VALUES (1, '/images/hero-room.png')
ON CONFLICT (id) DO UPDATE SET hero_image_url = EXCLUDED.hero_image_url;

INSERT INTO products (
  id,
  title,
  slug,
  subtitle,
  category,
  price,
  original_price,
  currency,
  image_url,
  active,
  sort_order,
  hotspot_x,
  hotspot_y,
  hotspot_width,
  hotspot_height,
  z_index,
  dimensions,
  stock,
  lead_time,
  badge,
  spatial_tag,
  description,
  story,
  specs,
  materials
)
VALUES
(
  'botanica-relief-art',
  'Botanica Gilded 3D Floral Wall Relief',
  'botanica-gilded-3d-floral-wall-relief',
  'Hand-Cast Porcelain & 24K Gold Leaf',
  'Fine Wall Sculptures',
  1420.00,
  NULL,
  'USD',
  '/products/botanica-relief-art.png',
  true,
  1,
  43.20,
  16.80,
  11.80,
  31.70,
  10,
  '62 cm × 94 cm × 8 cm',
  4,
  'Immediate White-Glove Dispatch',
  'Atelier Signature',
  'Salon Center Wall • Elevation +1.8m',
  'A centerpiece wall sculpture capturing three blooming white botanicals in sculptural relief. Textured gold leaf accents cascade beneath the petals, framed by hand-finished brushed champagne brass.',
  'Created in collaboration with Florentine master plaster artisans, each petal is hand-modeled in high-density porcelain plaster, layered over an antiqued parchment canvas with genuine 24-karat gold leaf textures.',
  '[{"label":"Dimensions","value":"62 cm W × 94 cm H × 8 cm D"},{"label":"Materials","value":"High-Density Plaster, 24K Gold Leaf, Solid Brass"},{"label":"Weight","value":"11.5 kg"},{"label":"Finish","value":"Matte Eggshell White & Brushed Antique Gold"},{"label":"Mounting","value":"Concealed French Cleat Hardware Included"}]'::jsonb,
  '["Porcelain Plaster","24K Gold Leaf","Champagne Brass Frame","Museum Glass Backing"]'::jsonb
),
(
  'indigo-velvet-loveseat',
  'Aria Indigo Stone-Washed Velvet Loveseat',
  'aria-indigo-stone-washed-velvet-loveseat',
  'Deep Double-Cushion Seating in Belgian Linen',
  'Living Room Seating',
  3850.00,
  4200.00,
  'USD',
  '/products/indigo-velvet-loveseat.png',
  true,
  2,
  34.50,
  54.80,
  34.20,
  37.40,
  10,
  '172 cm × 92 cm × 84 cm',
  2,
  'In Stock • Atelier White-Glove Delivery',
  'Masterwork Piece',
  'Salon Main Seating • Floor Datum',
  'Generously proportioned two-seater sofa upholstered in antiqued indigo Belgian linen velvet. Tailored with architectural track arms, goose down-wrapped core cushions, and tapered walnut block feet.',
  'Each sofa undergoes an artisanal stone-washing process that creates a bespoke celestial patina across the indigo velvet. The frame is hand-joined from kiln-dried European FSC beech hardwood with eight-way hand-tied springs.',
  '[{"label":"Overall Dimensions","value":"172 cm W × 92 cm D × 84 cm H"},{"label":"Seat Height","value":"46 cm"},{"label":"Seat Depth","value":"62 cm"},{"label":"Upholstery","value":"100% Belgian Washed Linen Velvet"},{"label":"Suspension","value":"8-Way Hand-Tied Steel Coil Springs"},{"label":"Frame","value":"FSC-Certified Solid European Beech"}]'::jsonb,
  '["Belgian Linen Velvet","Goose Down Blend","Solid European Beech","Cast Brass Glides"]'::jsonb
),
(
  'rattan-floor-lamp',
  'Solstice Handwoven Fringe Floor Lamp',
  'solstice-handwoven-fringe-floor-lamp',
  'Architectural Blackened Steel with Conical Rattan Shade',
  'Architectural Lighting',
  890.00,
  NULL,
  'USD',
  '/products/rattan-floor-lamp.png',
  true,
  3,
  58.20,
  29.80,
  10.00,
  51.40,
  12,
  '188 cm H × 54 cm Reach',
  6,
  'Dispatched in 48 Hours',
  'Architect Choice',
  'Salon Reading Nook • Floor +1.9m',
  'Cantilevered minimalist floor lamp pairing a slender blackened carbon steel stem with an artisanal conical lampshade woven from natural Indonesian rattan and finished with hand-knotted fringe tassels.',
  'Engineered to cast both ambient ambient warmth and functional downlight through its woven mesh texture. The counterbalanced geometric frame brings clean linear elegance to seating nooks.',
  '[{"label":"Overall Height","value":"188 cm"},{"label":"Reach / Depth","value":"54 cm"},{"label":"Shade Diameter","value":"44 cm"},{"label":"Lamp Socket","value":"E26 / Warm Amber LED 2200K Included"},{"label":"Cord","value":"3.2 m Braided Silk Charcoal Cable with Foot Switch"}]'::jsonb,
  '["Carbon Steel","Natural Rattan Cane","Raffia Fringe","Solid Brass Fittings"]'::jsonb
),
(
  'arch-bamboo-etagere',
  'Archipelago Cane & Bamboo Wall Étagère',
  'archipelago-cane-and-bamboo-wall-etagere',
  'Two-Tier Curved Bentwood Botanical Shelf',
  'Wall Shelving & Displays',
  1150.00,
  NULL,
  'USD',
  '/products/arch-bamboo-etagere.png',
  true,
  4,
  82.80,
  15.20,
  16.00,
  38.60,
  10,
  '72 cm × 104 cm × 24 cm',
  5,
  'In Stock • Courier Ready',
  'Artisan Crafted',
  'Right Salon Wall • Window Adjacent',
  'Gracefully arched wall shelving unit constructed from steam-bent natural rattan framing and vertical split bamboo slats. Two generous exhibition tiers bordered by intricate herringbone braidwork.',
  'Handcrafted on the island of Bali by third-generation cane masters. The vertical fluted bamboo backing creates subtle rhythmic light and shadow while securely cradling indoor botanicals and studio ceramics.',
  '[{"label":"Dimensions","value":"72 cm W × 104 cm H × 24 cm D"},{"label":"Tier Spacing","value":"36 cm Clear Height"},{"label":"Load Capacity","value":"18 kg per Shelf Tier"},{"label":"Material","value":"Indonesian Steam-Bent Cane & Bamboo Reed"},{"label":"Mounting","value":"Concealed Dual Heavy-Duty Brass Anchors"}]'::jsonb,
  '["Natural Honey Rattan","Fluted Bamboo","Hand-Braided Reed","Solid Brass Cleats"]'::jsonb
),
(
  'sunburst-rattan-mirror',
  'Helios Sunburst Woven Accent Mirror',
  'helios-sunburst-woven-accent-mirror',
  'Concentric Petal Bent-Cane Wall Mirror',
  'Artisanal Mirrors',
  620.00,
  NULL,
  'USD',
  '/products/sunburst-rattan-mirror.png',
  true,
  5,
  67.20,
  23.20,
  10.60,
  21.60,
  10,
  '82 cm Diameter × 4.5 cm D',
  7,
  'Immediate Dispatch',
  'Limited Series',
  'Side Wall • Mid-Level Reflection',
  'A luminous floral sunburst mirror crafted from concentric loops of steam-curved natural rattan peel. Centers a high-clarity bevel-edged silver float mirror that radiates warmth and bounce light throughout the room.',
  'Designed to evoke vintage Mediterranean villa aesthetics. Each petal loop is individually steamed and hand-lashed with organic vegetable fiber to a circular birch framework.',
  '[{"label":"Diameter","value":"82 cm Overall (36 cm Mirror Core)"},{"label":"Depth","value":"4.5 cm"},{"label":"Mirror Glass","value":"4 mm Ultra-Clear Float Glass with Polished Edge"},{"label":"Backing","value":"Engineered Baltic Birch with Heavy-Duty D-Rings"}]'::jsonb,
  '["Natural Rattan Core","Ultra-Clear Silver Mirror","Baltic Birch Backing"]'::jsonb
),
(
  'moroccan-berber-hamper',
  'Atlas Striped Moroccan Coil Hamper',
  'atlas-striped-moroccan-coil-hamper',
  'Hand-Spun Wool & Natural Palm Leaf with Conical Lid',
  'Artisanal Storage Vessels',
  440.00,
  NULL,
  'USD',
  '/products/moroccan-berber-hamper.png',
  true,
  6,
  32.20,
  69.20,
  10.60,
  26.00,
  25,
  '46 cm Dia × 74 cm H',
  5,
  'In Stock • Ready to Ship',
  'Fair Trade Heritage',
  'Salon Floor • Foreground Left',
  'Sculptural standing storage vessel coil-woven by Berber female artisans in the High Atlas mountains. Features alternating bands of saffron terracotta, slate gray, and ivory virgin wool yarn, topped with a braided knob.',
  'Taking over three weeks to weave on traditional coils, each vessel is an unrepeatable work of fiber art. The tight structural weave maintains its crisp cylindrical posture while providing generous hidden storage.',
  '[{"label":"Dimensions","value":"46 cm Diameter × 74 cm Total Height with Lid"},{"label":"Internal Volume","value":"78 Liters"},{"label":"Weave","value":"High-Density Wrapped Coil Stitch"},{"label":"Origin","value":"High Atlas Range, Morocco"}]'::jsonb,
  '["Atlas Mountain Virgin Wool","Organic Dried Palm Reed","Natural Mineral Dyes"]'::jsonb
),
(
  'wall-key-shelf',
  'Aura House Key & Display Shelf',
  'aura-house-key-and-display-shelf',
  'Solid American Walnut with Forged Brass Hooks',
  'Entryway Architectural Hardware',
  380.00,
  NULL,
  'USD',
  '/products/wall-key-shelf.png',
  true,
  7,
  13.80,
  21.80,
  12.40,
  27.20,
  10,
  '48 cm × 62 cm × 14 cm',
  8,
  'Dispatched in 24 Hours',
  'Curator Pick',
  'Entrance Doorway • Left Wall +1.5m',
  'Architectural gable-roof silhouette crafted from solid American walnut. Features vertical slats, an integrated display gallery shelf with retaining lip for photographs and succulents, and four hand-forged antique brass hooks.',
  'Rooted in mid-century alpine vernacular, this piece turns everyday key storage into a warm architectural moment upon crossing the threshold.',
  '[{"label":"Dimensions","value":"48 cm W × 62 cm H × 14 cm D"},{"label":"Ledge Depth","value":"11 cm Usable Gallery Depth"},{"label":"Wood","value":"Solid American Black Walnut (Hand-Oiled)"},{"label":"Hooks","value":"4 Solid Forged Antiqued Brass Utility Pegs"}]'::jsonb,
  '["Solid Black Walnut","Organic Danish Oil","Hand-Forged Brass"]'::jsonb
),
(
  'industrial-sconce',
  'Vanguard Industrial Pipe & Walnut Fixture',
  'vanguard-industrial-pipe-and-walnut-fixture',
  'Blackened Iron Pipe with Stitched Cognac Leather',
  'Architectural Wall Fixtures',
  510.00,
  NULL,
  'USD',
  '/products/industrial-sconce.png',
  true,
  8,
  28.80,
  22.20,
  7.20,
  29.60,
  10,
  '22 cm × 68 cm × 26 cm',
  6,
  'Immediate Dispatch',
  'Industrial Studio',
  'Salon Left Wall • Accent Pier',
  'Industrial-sculptural wall accent constructed with heavy-gauge malleable iron gas piping mounted against distressed charred pine timber, completed with a hand-stitched cognac bridle leather finial collar and crossed wrench hooks.',
  'Blending steam-era machinery with bespoke saddlery craft. The heavy industrial iron elements are hand-patinated with beeswax to resist oxidation while showcasing raw metallurgical texture.',
  '[{"label":"Dimensions","value":"22 cm W × 68 cm H × 26 cm Projection"},{"label":"Wood Backplate","value":"Reclaimed Distressed Hearth Pine"},{"label":"Piping","value":"3/4-inch Schedule 40 Malleable Iron"},{"label":"Leather","value":"Vegetable-Tanned Saddle Leather Collar"}]'::jsonb,
  '["Charred Hearth Pine","Malleable Black Iron","Cognac Saddle Leather"]'::jsonb
),
(
  'teak-accent-table',
  'Nordic Teak End Table & Terracotta Ensemble',
  'nordic-teak-end-table-and-terracotta-ensemble',
  'Grade-A Plantation Teak with Perforated Clay Urn',
  'Side Tables & Studio Ceramics',
  980.00,
  NULL,
  'USD',
  '/products/teak-accent-table.png',
  true,
  9,
  67.80,
  47.80,
  12.00,
  36.00,
  10,
  '56 cm × 56 cm × 62 cm',
  3,
  'In Stock • White-Glove Shipping',
  'Ensemble Set',
  'Salon Right Flank • Sofa Side',
  'Minimalist side table with slatted spindle side panels and lower library shelf, accompanied by an artisanal perforated terracotta urn containing dried meadow blooms.',
  'Constructed with traditional mortise-and-tenon joinery without visible metal screws. The accompanying terracotta urn is hand-pierced by ceramicists in Seville before firing at 1050°C.',
  '[{"label":"Table Dimensions","value":"56 cm W × 56 cm D × 62 cm H"},{"label":"Vase Dimensions","value":"26 cm Dia × 38 cm H"},{"label":"Wood","value":"Grade-A Sustainable Plantation Teak"},{"label":"Ceramics","value":"Unglazed Spanish Terracotta with Pierced Apertures"}]'::jsonb,
  '["Grade-A Teak","Hand-Thrown Terracotta Clay","Natural Beeswax Polish"]'::jsonb
),
(
  'open-weave-floor-basket',
  'Palma Open-Weave Rattan Floor Vessel',
  'palma-open-weave-rattan-floor-vessel',
  'Parabolic Cane Arch Ribbed Accent Basket',
  'Artisanal Floor Baskets',
  320.00,
  NULL,
  'USD',
  '/products/open-weave-floor-basket.png',
  true,
  10,
  76.20,
  73.20,
  10.60,
  21.00,
  25,
  '44 cm Dia × 56 cm H',
  9,
  'Dispatched in 24 Hours',
  'Bohemian Scandi',
  'Floor Foreground • Rug Border',
  'Sculptural open-frame basket constructed with parabolic bent rattan loops that form an airy cage structure with integrated sculpted loop carry handles.',
  'The rhythmic vertical lines create striking shadow patterns on floorboards when hit by daylight. Ideal for storing cashmere throws, architectural blueprints, or standing as an organic sculpture.',
  '[{"label":"Dimensions","value":"44 cm Oval Dia × 56 cm H to Top of Handles"},{"label":"Base","value":"Solid Multi-Layer Woven Rattan Webbing Core"},{"label":"Weight","value":"2.4 kg"},{"label":"Finish","value":"Clear Matte Water-Based Protective Seal"}]'::jsonb,
  '["Natural Indonesian Rattan","Steam-Bent Cane Arches"]'::jsonb
),
(
  'monstera-terracotta-urn',
  'Monstera Deliciosa in Clay Planter',
  'monstera-deliciosa-in-clay-planter',
  'Mature Architectural Botanical in Mineral-Wash Urn',
  'Botanical Accents',
  290.00,
  NULL,
  'USD',
  '/products/monstera-terracotta-urn.png',
  true,
  11,
  84.80,
  59.80,
  15.00,
  36.40,
  20,
  '95 cm Total Height • 38 cm Pot',
  6,
  'White-Glove Courier with Botanical Guarantee',
  'Living Decor',
  'Right Salon Corner • Sunlit Floor',
  'Flourishing multi-stem Swiss Cheese Plant featuring large perforated glossy green leaves, housed in a heavyweight Italian red clay cylindrical planter with rolled rim and drainage saucer.',
  'Cultivated in organic sustainable Mediterranean nurseries. The porous unglazed clay planter promotes root respiration and develops a natural organic verdigris patina over the years.',
  '[{"label":"Plant Height","value":"Approx. 95 cm to 110 cm from Floor"},{"label":"Planter Dimensions","value":"38 cm Outer Dia × 36 cm H"},{"label":"Pot Material","value":"Tuscan Impruneta Frost-Proof Red Terracotta"},{"label":"Care Requirements","value":"Bright Indirect Light • Weekly Watering"}]'::jsonb,
  '["Living Monstera Botanical","Tuscan Terracotta Clay","Organic Pumice Soil Blend"]'::jsonb
),
(
  'isfahan-heirloom-rug',
  'Isfahan Hand-Knotted Heritage Wool Rug',
  'isfahan-hand-knotted-heritage-wool-rug',
  'Vegetable-Dyed Persian Knotwork with Geometric Medallion',
  'Heirloom Floor Textiles',
  2750.00,
  3100.00,
  'USD',
  '/products/isfahan-heirloom-rug.png',
  true,
  12,
  42.80,
  82.20,
  47.40,
  17.60,
  5,
  '245 cm × 165 cm',
  1,
  'Unique Masterwork • Dispatched in Climate-Proof Box',
  'One of a Kind',
  'Salon Floor Centerpiece • 4.0 m²',
  'Heirloom masterwork area rug featuring a central diamond medallion surrounded by nomadic zoomorphic motifs in saffron, deep indigo, burnt sienna, and sage green vegetable dyes.',
  'Over 400 hours of single-needle hand-knotting by master weavers using handspun high-plateau highland wool. Each knot is individually sheared to create a silky, durable low-pile texture.',
  '[{"label":"Dimensions","value":"245 cm L × 165 cm W (Approx. 8.0 ft × 5.4 ft)"},{"label":"Knot Density","value":"320 Knots per Square Inch (KPSI)"},{"label":"Pile Height","value":"8 mm Low-Profile Velvet Hand"},{"label":"Dyes","value":"100% Organic Indigo, Madder Root, Saffron, Walnut Husk"},{"label":"Fringe","value":"Hand-Finished Unbleached Cotton Fringe"}]'::jsonb,
  '["Highland Handspun Wool","Vegetable Dyes","Organic Cotton Warp & Weft"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  subtitle = EXCLUDED.subtitle,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  image_url = EXCLUDED.image_url,
  active = EXCLUDED.active,
  sort_order = EXCLUDED.sort_order,
  hotspot_x = EXCLUDED.hotspot_x,
  hotspot_y = EXCLUDED.hotspot_y,
  hotspot_width = EXCLUDED.hotspot_width,
  hotspot_height = EXCLUDED.hotspot_height,
  z_index = EXCLUDED.z_index,
  description = EXCLUDED.description,
  story = EXCLUDED.story,
  specs = EXCLUDED.specs,
  materials = EXCLUDED.materials;
